### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by jmakanjuola** [publicsoftware/OpenBI#1]
What's the default username and password?

**Comment by kookiatsuetrong** [comment]
For the code that you cloned: root / password
For the online demo (http://openbi.publicsoftwareproject.org): user / user

**Comment by jmakanjuola** [comment]
Thanks! Kookiat. I find your project to be interesting and I was wondering how we can collaborate on integrating the concert with our project. Are you on Skpye?

**Comment by kookiatsuetrong** [comment]
My email is kookiat at kookiat.com or twitter is @kookiatsuetrong .
